### model
model_name_or_path: 'D:\Repositories\20260305_local_LLM\model\Qwen3-4B'
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: preexp4_pa5_taskrand_hanzi_train
eval_dataset: preexp4_pa5_taskrand_hanzi_val
template: qwen3_nothink
cutoff_len: 1024
preprocessing_num_workers: 2
dataloader_num_workers: 0

### output
output_dir: 'D:\Repositories\20260319_sylb-prob-mat2char-acc\new_task_4_finetune\reports\pa5_taskrand_hanzi\adapter'
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 8.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
seed: 42
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
